apiVersion: v1
kind: Service
metadata:
  name: bidders
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: bidders
spec:

  ports:
  - name: http
    port: {{ .Values.service.internalPort }}
  selector:
    app: bidders
