apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projects
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: projects
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
      - image: "{{ .Values.image.repository }}"
        name: projects
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
