apiVersion: v1
kind: Service
metadata:
  name: projects
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: projects
spec:
  ports:
  - name: http
    port: {{ .Values.service.internalPort }}
  selector:
    app: projects
